/*
 * Soliguide: Useful information for those who need it
 *
 * SPDX-FileCopyrightText: © 2024 Solinum
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
import { TerritoriesNotif } from "../types";

export const TERRITORIES_NOTIF: TerritoriesNotif = {
  "01": {
    senderEmail: "ain@solinum.org",
    senderFirstName: "L'équipe Soliguide Ain",
    senderName: "Solinum Ain",
    slug: "ain",
  },
  "02": {
    senderEmail: "contact@solinum.org",
    senderFirstName: "L'équipe Soliguide Aisne",
    senderName: "Solinum Aisne",
    slug: "aisne",
  },
  "03": {
    senderEmail: "contact@solinum.org",
    senderFirstName: "L'équipe Soliguide Allier",
    senderName: "Solinum Allier",
    slug: "allier",
  },
  "04": {
    senderEmail: "alpesdehauteprovence@solinum.org",
    senderFirstName: "L'équipe Soliguide Alpes-de-Haute-Provence",
    senderName: "Solinum Alpes-de-Haute-Provence",
    slug: "alpes-de-haute-provence",
  },
  "05": {
    senderEmail: "hautesalpes@solinum.org",
    senderFirstName: "L'équipe Soliguide Hautes-Alpes",
    senderName: "Solinum Hautes-Alpes",
    slug: "hautes-alpes",
  },
  "06": {
    senderEmail: "alpesmaritimes@solinum.org",
    senderFirstName: "Perrine de Soliguide",
    senderName: "Solinum Alpes-Maritimes",
    slug: "alpes-maritimes",
  },
  "07": {
    senderEmail: "ardeche@solinum.org",
    senderFirstName: "Manal de Soliguide",
    senderName: "Solinum Ardèche",
    slug: "ardeche",
  },
  "08": {
    senderEmail: "ardennes@solinum.org",
    senderFirstName: "L'équipe Soliguide Ardennes",
    senderName: "Solinum Ardennes",
    slug: "ardennes",
  },
  "09": {
    senderEmail: "ariege@solinum.org",
    senderFirstName: "L'équipe Soliguide Ariège",
    senderName: "Solinum Ariège",
    slug: "ariege",
  },
  "10": {
    senderEmail: "aube@solinum.org",
    senderFirstName: "L'équipe Soliguide Aube",
    senderName: "Solinum Aube",
    slug: "aube",
  },
  "11": {
    senderEmail: "aude@solinum.org",
    senderFirstName: "L'équipe Soliguide Aude",
    senderName: "Solinum Aude",
    slug: "aude",
  },
  "12": {
    senderEmail: "aveyron@solinum.org",
    senderFirstName: "L'équipe Soliguide Aveyron",
    senderName: "Solinum Aveyron",
    slug: "aveyron",
  },
  "13": {
    senderEmail: "bouchesdurhone@solinum.org",
    senderFirstName: "Léna de Soliguide",
    senderName: "Solinum Bouches-du-Rhône",
    slug: "bouches-du-rhone",
  },
  "14": {
    senderEmail: "calvados@solinum.org",
    senderFirstName: "L'équipe Soliguide Calvados",
    senderName: "Solinum Calvados",
    slug: "calvados",
  },
  "15": {
    senderEmail: "cantal@soliguide.fr",
    senderFirstName: "L'équipe Soliguide Cantal",
    senderName: "Solinum Cantal",
    slug: "cantal",
  },
  "16": {
    senderEmail: "charente@solinum.org",
    senderFirstName: "Sarah de Soliguide",
    senderName: "Solinum Charente",
    slug: "charente",
  },
  "17": {
    senderEmail: "charentemaritime@solinum.org",
    senderFirstName: "L'équipe Soliguide Charente-Maritime",
    senderName: "Solinum Charente-Maritime",
    slug: "charente-maritime",
  },
  "18": {
    senderEmail: "cher@soliguide.fr",
    senderFirstName: "Tiphaine, Zoé et Antoine de Soliguide",
    senderName: "Solinum Cher",
    slug: "cher",
  },
  "19": {
    senderEmail: "correze@solinum.org",
    senderFirstName: "L'équipe Soliguide Corrèze",
    senderName: "Solinum Corrèze",
    slug: "correze",
  },
  "2A": {
    senderEmail: "corsedusud@solinum.org",
    senderFirstName: "L'équipe Soliguide Corse-du-Sud",
    senderName: "Solinum Corse-du-Sud",
    slug: "corse-du-sud",
  },
  "2B": {
    senderEmail: "hautecorse@solinum.org",
    senderFirstName: "L'équipe Soliguide Haute-Corse",
    senderName: "Solinum Haute-Corse",
    slug: "haute-corse",
  },
  "21": {
    senderEmail: "cotedor@soliguide.fr",
    senderFirstName: "Agathe de Soliguide",
    senderName: "Solinum Côte-d'Or",
    slug: "cote-or",
  },
  "22": {
    senderEmail: "cotesdarmor@soliguide.fr",
    senderFirstName: "François de Soliguide",
    senderName: "Solinum Côtes-d'Armor",
    slug: "cotes-armor",
  },
  "23": {
    senderEmail: "creuse@solinum.org",
    senderFirstName: "L'équipe Soliguide Creuse",
    senderName: "Solinum Creuse",
    slug: "creuse",
  },
  "24": {
    senderEmail: "dordogne@solinum.org",
    senderFirstName: "Anna de Soliguide",
    senderName: "Solinum Dordogne",
    slug: "dordogne",
  },
  "25": {
    senderEmail: "doubs@solinum.org",
    senderFirstName: "L'équipe Soliguide Doubs",
    senderName: "Solinum Doubs",
    slug: "doubs",
  },
  "26": {
    senderEmail: "drome@solinum.org",
    senderFirstName: "L'équipe Soliguide Drôme",
    senderName: "Solinum Drôme",
    slug: "drome",
  },
  "27": {
    senderEmail: "eure@solinum.org",
    senderFirstName: "L'équipe Soliguide Eure",
    senderName: "Solinum Eure",
    slug: "eure",
  },
  "28": {
    senderEmail: "eureetloir@solinum.org",
    senderFirstName: "L'équipe Soliguide Eure-et-Loir",
    senderName: "Solinum Eure-et-Loir",
    slug: "eure-et-loir",
  },
  "29": {
    senderEmail: "finistere@solinum.org",
    senderFirstName: "L'équipe Soliguide Finistère",
    senderName: "Solinum Finistère",
    slug: "finistere",
  },
  "30": {
    senderEmail: "gard@solinum.org",
    senderFirstName: "Robin de Soliguide",
    senderName: "Solinum Gard",
    slug: "gard",
  },
  "31": {
    senderEmail: "hautegaronne@solinum.org",
    senderFirstName: "Maud de Soliguide",
    senderName: "Solinum Haute-Garonne",
    slug: "haute-garonne",
  },
  "32": {
    senderEmail: "gers@solinum.org",
    senderFirstName: "L'équipe Soliguide Gers",
    senderName: "Solinum Gers",
    slug: "gers",
  },
  "33": {
    senderEmail: "gironde@solinum.org",
    senderFirstName: "L'équipe Soliguide Gironde",
    senderName: "Solinum Gironde",
    slug: "gironde",
  },
  "34": {
    senderEmail: "herault@solinum.org",
    senderFirstName: "Andrea de Soliguide",
    senderName: "Solinum Hérault",
    slug: "herault",
  },
  "35": {
    senderEmail: "illeetvilaine@solinum.org",
    senderFirstName: "L'équipe Soliguide Ille-et-Vilaine",
    senderName: "Solinum Ille-et-Vilaine",
    slug: "ille-et-vilaine",
  },
  "36": {
    senderEmail: "indre@soliguide.fr",
    senderFirstName: "Marie de Soliguide",
    senderName: "Solinum Indre",
    slug: "indre",
  },
  "37": {
    senderEmail: "indreetloire@solinum.org",
    senderFirstName: "L'équipe Soliguide Indre-et-Loire",
    senderName: "Solinum Indre-et-Loire",
    slug: "indre-et-loire",
  },
  "38": {
    senderEmail: "isere@solinum.org",
    senderFirstName: "L'équipe Soliguide Isère",
    senderName: "Solinum Isère",
    slug: "isere",
  },
  "39": {
    senderEmail: "jura@solinum.org",
    senderFirstName: "L'équipe Soliguide Jura",
    senderName: "Solinum Jura",
    slug: "jura",
  },
  "40": {
    senderEmail: "landes@solinum.org",
    senderFirstName: "L'équipe Soliguide Landes",
    senderName: "Solinum Landes",
    slug: "landes",
  },
  "41": {
    senderEmail: "loiretcher@solinum.org",
    senderFirstName: "L'équipe Soliguide Loir-et-Cher",
    senderName: "Solinum Loir-et-Cher",
    slug: "loir-et-cher",
  },
  "42": {
    senderEmail: "loire@soliguide.fr",
    senderFirstName: "L'équipe Soliguide Loire",
    senderName: "Solinum Loire",
    slug: "loire",
  },
  "43": {
    senderEmail: "hauteloire@solinum.org",
    senderFirstName: "L'équipe Soliguide Haute-Loire",
    senderName: "Solinum Haute-Loire",
    slug: "haute-loire",
  },
  "44": {
    senderEmail: "loireatlantique@solinum.org",
    senderFirstName: "L'équipe Soliguide Loire-Atlantique",
    senderName: "Solinum Loire-Atlantique",
    slug: "loire-atlantique",
  },
  "45": {
    senderEmail: "loiret@solinum.org",
    senderFirstName: "L'équipe Soliguide Loiret",
    senderName: "Solinum Loiret",
    slug: "loiret",
  },
  "46": {
    senderEmail: "lot@solinum.org",
    senderFirstName: "L'équipe Soliguide Lot",
    senderName: "Solinum Lot",
    slug: "lot",
  },
  "47": {
    senderEmail: "lotetgaronne@solinum.org",
    senderFirstName: "L'équipe Soliguide Lot-et-Garonne",
    senderName: "Solinum Lot-et-Garonne",
    slug: "lot-et-garonne",
  },
  "48": {
    senderEmail: "lozere@solinum.org",
    senderFirstName: "L'équipe Soliguide Lozère",
    senderName: "Solinum Lozère",
    slug: "lozere",
  },
  "49": {
    senderEmail: "maineetloire@solinum.org",
    senderFirstName: "L'équipe Soliguide Maine-et-Loire",
    senderName: "Solinum Maine-et-Loire",
    slug: "maine-et-loire",
  },
  "50": {
    senderEmail: "manche@solinum.org",
    senderFirstName: "L'équipe Soliguide Manche",
    senderName: "Solinum Manche",
    slug: "manche",
  },
  "51": {
    senderEmail: "marne@solinum.org",
    senderFirstName: "L'équipe Soliguide Marne",
    senderName: "Solinum Marne",
    slug: "marne",
  },
  "52": {
    senderEmail: "hautemarne@solinum.org",
    senderFirstName: "L'équipe Soliguide Haute-Marne",
    senderName: "Solinum Haute-Marne",
    slug: "haute-marne",
  },
  "53": {
    senderEmail: "mayenne@solinum.org",
    senderFirstName: "L'équipe Soliguide Mayenne",
    senderName: "Solinum Mayenne",
    slug: "mayenne",
  },
  "54": {
    senderEmail: "meurtheetmoselle@solinum.org",
    senderFirstName: "L'équipe Soliguide Meurthe-et-Moselle",
    senderName: "Solinum Meurthe-et-Moselle",
    slug: "meurthe-et-moselle",
  },
  "55": {
    senderEmail: "meuse@solinum.org",
    senderFirstName: "L'équipe Soliguide Meuse",
    senderName: "Solinum Meuse",
    slug: "meuse",
  },
  "56": {
    senderEmail: "morbihan@solinum.org",
    senderFirstName: "Mathilde de Soliguide",
    senderName: "Solinum Morbihan",
    slug: "morbihan",
  },
  "57": {
    senderEmail: "moselle@solinum.org",
    senderFirstName: "L'équipe Soliguide Moselle",
    senderName: "Solinum Moselle",
    slug: "moselle",
  },
  "58": {
    senderEmail: "nievre@solinum.org",
    senderFirstName: "L'équipe Soliguide Nièvre",
    senderName: "Solinum Nièvre",
    slug: "nievre",
  },
  "59": {
    senderEmail: "nord@solinum.org",
    senderFirstName: "Gabrielle de Soliguide",
    senderName: "Solinum Nord",
    slug: "nord",
  },
  "60": {
    senderEmail: "oise@solinum.org",
    senderFirstName: "L'équipe Soliguide Oise",
    senderName: "Solinum Oise",
    slug: "oise",
  },
  "61": {
    senderEmail: "orne@solinum.org",
    senderFirstName: "L'équipe Soliguide Orne",
    senderName: "Solinum Orne",
    slug: "orne",
  },
  "62": {
    senderEmail: "pasdecalais@solinum.org",
    senderFirstName: "L'équipe Soliguide Pas-de-Calais",
    senderName: "Solinum Pas-de-Calais",
    slug: "pas-de-calais",
  },
  "63": {
    senderEmail: "puydedome@soliguide.fr",
    senderFirstName: "Fanta et Cécile de Soliguide",
    senderName: "Solinum Puy-de-Dôme",
    slug: "puy-de-dome",
  },
  "64": {
    senderEmail: "pyreneesatlantiques@solinum.org",
    senderFirstName: "L'équipe Soliguide Pyrénées-Atlantiques",
    senderName: "Solinum Pyrénées-Atlantiques",
    slug: "pyrenees-atlantiques",
  },
  "65": {
    senderEmail: "hautespyrenees@solinum.org",
    senderFirstName: "L'équipe Soliguide Hautes-Pyrénées",
    senderName: "Solinum Hautes-Pyrénées",
    slug: "hautes-pyrenees",
  },
  "66": {
    senderEmail: "pyreneesorientales@solinum.org",
    senderFirstName: "L'équipe Soliguide Pyrénées-Orientales",
    senderName: "Solinum Pyrénées-Orientales",
    slug: "pyrenees-orientales",
  },
  "67": {
    senderEmail: "basrhin@solinum.org",
    senderFirstName: "Philippe de Soliguide",
    senderName: "Solinum Bas-Rhin",
    slug: "bas-rhin",
  },
  "68": {
    senderEmail: "hautrhin@solinum.org",
    senderFirstName: "Laetitia de Soliguide",
    senderName: "Solinum Haut-Rhin",
    slug: "haut-rhin",
  },
  "69": {
    senderEmail: "rhone@solinum.org",
    senderFirstName: "L'équipe Soliguide Rhône",
    senderName: "Solinum Rhône",
    slug: "rhone",
  },
  "70": {
    senderEmail: "hautesaone@solinum.org",
    senderFirstName: "L'équipe Soliguide Haute-Saône",
    senderName: "Solinum Haute-Saône",
    slug: "haute-saone",
  },
  "71": {
    senderEmail: "saoneetloire@solinum.org",
    senderFirstName: "L'équipe Soliguide Saône-et-Loire",
    senderName: "Solinum Saône-et-Loire",
    slug: "saone-et-loire",
  },
  "72": {
    senderEmail: "sarthe@solinum.org",
    senderFirstName: "L'équipe Soliguide Sarthe",
    senderName: "Solinum Sarthe",
    slug: "sarthe",
  },
  "73": {
    senderEmail: "savoie@solinum.org",
    senderFirstName: "L'équipe Soliguide Savoie",
    senderName: "Solinum Savoie",
    slug: "savoie",
  },
  "74": {
    senderEmail: "annecy@soliguide.fr",
    senderFirstName: "Florence de Soliguide",
    senderName: "Solinum Haute-Savoie",
    slug: "haute-savoie",
  },
  "75": {
    senderEmail: "paris@solinum.org",
    senderFirstName: "Alexine de Soliguide",
    senderName: "Solinum Paris",
    slug: "paris",
  },
  "76": {
    senderEmail: "seinemaritime@solinum.org",
    senderFirstName: "Amandine de Soliguide",
    senderName: "Solinum Seine-Maritime",
    slug: "seine-maritime",
  },
  "77": {
    senderEmail: "seineetmarne@solinum.org",
    senderFirstName: "Kevin de Soliguide",
    senderName: "Solinum Seine-et-Marne",
    slug: "seine-et-marne",
  },
  "78": {
    senderEmail: "yvelines@solinum.org",
    senderFirstName: "Cassandre de Soliguide",
    senderName: "Solinum Yvelines",
    slug: "yvelines",
  },
  "79": {
    senderEmail: "deuxsevres@solinum.org",
    senderFirstName: "L'équipe Soliguide Deux-Sèvres",
    senderName: "Solinum Deux-Sèvres",
    slug: "deux-sevres",
  },
  "80": {
    senderEmail: "somme@solinum.org",
    senderFirstName: "L'équipe Soliguide Somme",
    senderName: "Solinum Somme",
    slug: "somme",
  },
  "81": {
    senderEmail: "tarn@solinum.org",
    senderFirstName: "L'équipe Soliguide Tarn",
    senderName: "Solinum Tarn",
    slug: "tarn",
  },
  "82": {
    senderEmail: "tarnetgaronne@solinum.org",
    senderFirstName: "L'équipe Soliguide Tarn-et-Garonne",
    senderName: "Solinum Tarn-et-Garonne",
    slug: "tarn-et-garonne",
  },
  "83": {
    senderEmail: "var@solinum.org",
    senderFirstName: "L'équipe Soliguide Var",
    senderName: "Solinum Var",
    slug: "var",
  },
  "84": {
    senderEmail: "vaucluse@solinum.org",
    senderFirstName: "L'équipe Soliguide Vaucluse",
    senderName: "Solinum Vaucluse",
    slug: "vaucluse",
  },
  "85": {
    senderEmail: "vendee@solinum.org",
    senderFirstName: "L'équipe Soliguide Vendée",
    senderName: "Solinum Vendée",
    slug: "vendee",
  },
  "86": {
    senderEmail: "vienne@solinum.org",
    senderFirstName: "Antoine de Soliguide",
    senderName: "Solinum Vienne",
    slug: "vienne",
  },
  "87": {
    senderEmail: "hautevienne@solinum.org",
    senderFirstName: "Anna de Soliguide",
    senderName: "Solinum Haute-Vienne",
    slug: "haute-vienne",
  },
  "88": {
    senderEmail: "vosges@solinum.org",
    senderFirstName: "L'équipe Soliguide Vosges",
    senderName: "Solinum Vosges",
    slug: "vosges",
  },
  "89": {
    senderEmail: "yonne@solinum.org",
    senderFirstName: "L'équipe Soliguide Yonne",
    senderName: "Solinum Yonne",
    slug: "yonne",
  },
  "90": {
    senderEmail: "territoiredebelfort@solinum.org",
    senderFirstName: "L'équipe Soliguide Territoire de Belfort",
    senderName: "Solinum Territoire de Belfort",
    slug: "territoire-de-belfort",
  },
  "91": {
    senderEmail: "essonne@solinum.org",
    senderFirstName: "Gaëlle de Soliguide",
    senderName: "Solinum Essonne",
    slug: "essonne",
  },
  "92": {
    senderEmail: "hautsdeseine@solinum.org",
    senderFirstName: "Cassandre de Soliguide",
    senderName: "Solinum Hauts-de-Seine",
    slug: "hauts-de-seine",
  },
  "93": {
    senderEmail: "seinesaintdenis@solinum.org",
    senderFirstName: "Léo de Soliguide",
    senderName: "Solinum Seine-Saint-Denis",
    slug: "seine-saint-denis",
  },
  "94": {
    senderEmail: "valdemarne@solinum.org",
    senderFirstName: "Gaëlle de Soliguide",
    senderName: "Solinum Val-de-Marne",
    slug: "val-de-marne",
  },
  "95": {
    senderEmail: "valdoise@solinum.org",
    senderFirstName: "Inti de Soliguide",
    senderName: "Solinum Val-d'Oise",
    slug: "val-oise",
  },
  "971": {
    senderEmail: "guadeloupe@solinum.org",
    senderFirstName: "L'équipe Soliguide Guadeloupe",
    senderName: "Solinum Guadeloupe",
    slug: "guadeloupe",
  },
  "972": {
    senderEmail: "martinique@solinum.org",
    senderFirstName: "L'équipe Soliguide Martinique",
    senderName: "Solinum Martinique",
    slug: "martinique",
  },
  "973": {
    senderEmail: "guyane@solinum.org",
    senderFirstName: "L'équipe Soliguide Guyane",
    senderName: "Solinum Guyane",
    slug: "guyane",
  },
  "974": {
    senderEmail: "lareunion@solinum.org",
    senderFirstName: "Ariane de Soliguide",
    senderName: "Solinum La Réunion",
    slug: "la-reunion",
  },
  "976": {
    senderEmail: "mayotte@solinum.org",
    senderFirstName: "L'équipe Soliguide Mayotte",
    senderName: "Solinum Mayotte",
    slug: "mayotte",
  },
  "975": {
    senderEmail: "contact@solinum.org",
    senderFirstName: "L'équipe Soliguide Saint-Pierre-et-Miquelon",
    senderName: "Solinum Saint-Pierre-et-Miquelon",
    slug: "saint-pierre-et-miquelon",
  },
  "977": {
    senderEmail: "contact@solinum.org",
    senderFirstName: "L'équipe Soliguide Saint-Barthélemy",
    senderName: "Solinum Saint-Barthélemy",
    slug: "saint-barthelemy",
  },
  "978": {
    senderEmail: "contact@solinum.org",
    senderFirstName: "L'équipe Soliguide Saint-Martin",
    senderName: "Solinum Saint-Martin",
    slug: "saint-martin",
  },
  "984": {
    senderEmail: "contact@solinum.org",
    senderFirstName: "L'équipe Soliguide Terres australes françaises",
    senderName: "Solinum Terres australes françaises",
    slug: "terres-australes-francaises",
  },
  "986": {
    senderEmail: "contact@solinum.org",
    senderFirstName: "L'équipe Soliguide Wallis-et-Futuna",
    senderName: "Solinum Wallis-et-Futuna",
    slug: "wallis-et-futuna",
  },
  "987": {
    senderEmail: "contact@solinum.org",
    senderFirstName: "L'équipe Soliguide Polynésie Française",
    senderName: "Solinum Polynésie Française",
    slug: "polynesie-francaise",
  },
  "988": {
    senderEmail: "contact@solinum.org",
    senderFirstName: "L'équipe Soliguide Nouvelle Calédonie",
    senderName: "Solinum Nouvelle Calédonie",
    slug: "nouvelle-caledonie",
  },
};
