/*
 * Soliguide: Useful information for those who need it
 *
 * SPDX-FileCopyrightText: © 2024 Solinum
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
// https://fr.wikipedia.org/wiki/Liste_des_d%C3%A9partements_fran%C3%A7ais

import { CountryCodes } from "../../enums";
import { RegionDef } from "../../interfaces";

export const FR_REGIONS_DEF: Array<RegionDef<CountryCodes.FR>> = [
  {
    regionCode: "01",
    regionName: "Guadeloupe",
    isoCode: "FR-971",
    subdivisionShortName: "GP",
    schoolZoneShortName: "GP",
    slug: "guadeloupe",
    timeZone: "America/Martinique",
    departments: [
      {
        departmentCode: "971",
        departmentName: "Guadeloupe",
        isoCode: "FR-971",
        subdivisionShortName: "GP",
        schoolZoneShortName: "GP",
        coordinates: [-61.487996, 16.206931],
      },
    ],
    coordinates: [-61.487996, 16.206931],
  },
  {
    regionCode: "02",
    regionName: "Martinique",
    isoCode: "FR-972",
    subdivisionShortName: "MQ",
    schoolZoneShortName: "MQ",
    slug: "martinique",
    timeZone: "America/Martinique",
    departments: [
      {
        departmentCode: "972",
        departmentName: "Martinique",
        isoCode: "FR-972",
        subdivisionShortName: "MQ",
        schoolZoneShortName: "MQ",
        coordinates: [-60.94789, 14.602637],
      },
    ],
    coordinates: [-60.94789, 14.602637],
  },
  {
    regionCode: "03",
    regionName: "Guyane",
    isoCode: "FR-973",
    subdivisionShortName: "GY",
    schoolZoneShortName: "GY",
    slug: "guyane",
    timeZone: "America/Cayenne",
    departments: [
      {
        departmentCode: "973",
        departmentName: "Guyane",
        isoCode: "FR-973",
        subdivisionShortName: "GY",
        schoolZoneShortName: "GY",
        coordinates: [-53.183642, 3.720608],
      },
    ],
    coordinates: [-53.183642, 3.720608],
  },
  {
    regionCode: "04",
    regionName: "La Réunion",
    isoCode: "FR-974",
    subdivisionShortName: "RU",
    schoolZoneShortName: "RU",
    slug: "la-reunion",
    timeZone: "Indian/Reunion",
    departments: [
      {
        departmentCode: "974",
        departmentName: "La Réunion",
        isoCode: "FR-974",
        subdivisionShortName: "RU",
        schoolZoneShortName: "RU",
        coordinates: [55.513348, -21.164501],
      },
    ],
    coordinates: [55.513348, -21.164501],
  },
  {
    regionCode: "06",
    regionName: "Mayotte",
    isoCode: "FR-976",
    subdivisionShortName: "YT",
    schoolZoneShortName: "YT",
    slug: "mayotte",
    timeZone: "Indian/Mayotte",
    departments: [
      {
        departmentCode: "976",
        departmentName: "Mayotte",
        isoCode: "FR-976",
        subdivisionShortName: "YT",
        schoolZoneShortName: "YT",
        coordinates: [45.155103, -12.814881],
      },
    ],
    coordinates: [45.155103, -12.814881],
  },
  {
    regionCode: "11",
    regionName: "Île-de-France",
    isoCode: "FR-IDF",
    schoolZoneShortName: "ZC",
    timeZone: "Europe/Paris",
    slug: "ile-de-france",
    departments: [
      {
        departmentCode: "75",
        departmentName: "Paris",
        isoCode: "FR-75C",
        schoolZoneShortName: "ZC",
        coordinates: [2.362203, 48.846223],
      },
      {
        departmentCode: "77",
        departmentName: "Seine-et-Marne",
        isoCode: "FR-77",
        schoolZoneShortName: "ZC",
        coordinates: [2.949703, 48.64091],
      },
      {
        departmentCode: "78",
        departmentName: "Yvelines",
        isoCode: "FR-78",
        schoolZoneShortName: "ZC",
        coordinates: [1.828046, 48.792871],
      },
      {
        departmentCode: "91",
        departmentName: "Essonne",
        isoCode: "FR-91",
        schoolZoneShortName: "ZC",
        coordinates: [2.238797, 48.531332],
      },
      {
        departmentCode: "92",
        departmentName: "Hauts-de-Seine",
        isoCode: "FR-92",
        schoolZoneShortName: "ZC",
        coordinates: [2.250681, 48.814825],
      },
      {
        departmentCode: "93",
        departmentName: "Seine-Saint-Denis",
        isoCode: "FR-93",
        schoolZoneShortName: "ZC",
        coordinates: [2.502605, 48.923555],
      },
      {
        departmentCode: "94",
        departmentName: "Val-de-Marne",
        isoCode: "FR-94",
        schoolZoneShortName: "ZC",
        coordinates: [2.479868, 48.770561],
      },
      {
        departmentCode: "95",
        departmentName: "Val-d'Oise",
        isoCode: "FR-95",
        schoolZoneShortName: "ZC",
        coordinates: [2.083741, 49.102974],
      },
    ],
    coordinates: [2.496865, 48.730534],
  },
  {
    regionCode: "24",
    regionName: "Centre-Val de Loire",
    isoCode: "FR-CVL",
    schoolZoneShortName: "ZB",
    timeZone: "Europe/Paris",
    slug: "centre-val-de-loire",
    departments: [
      {
        departmentCode: "18",
        departmentName: "Cher",
        isoCode: "FR-18",
        schoolZoneShortName: "ZB",
        coordinates: [2.394086, 46.993659],
      },
      {
        departmentCode: "28",
        departmentName: "Eure-et-Loir",
        isoCode: "FR-28",
        schoolZoneShortName: "ZB",
        coordinates: [1.356137, 48.409707],
      },
      {
        departmentCode: "36",
        departmentName: "Indre",
        isoCode: "FR-36",
        schoolZoneShortName: "ZB",
        coordinates: [1.590607, 46.719993],
      },
      {
        departmentCode: "37",
        departmentName: "Indre-et-Loire",
        isoCode: "FR-37",
        schoolZoneShortName: "ZB",
        coordinates: [0.668143, 47.274559],
      },
      {
        departmentCode: "41",
        departmentName: "Loir-et-Cher",
        isoCode: "FR-41",
        schoolZoneShortName: "ZB",
        coordinates: [1.333241, 47.697403],
      },
      {
        departmentCode: "45",
        departmentName: "Loiret",
        isoCode: "FR-45",
        schoolZoneShortName: "ZB",
        coordinates: [2.345241, 47.931968],
      },
    ],
    coordinates: [1.571313, 47.635239],
  },
  {
    regionCode: "27",
    regionName: "Bourgogne-Franche-Comté",
    isoCode: "FR-BFC",
    schoolZoneShortName: "ZA",
    timeZone: "Europe/Paris",
    slug: "bourgogne-franche-comte",
    departments: [
      {
        departmentCode: "21",
        departmentName: "Côte-d'Or",
        isoCode: "FR-21",
        schoolZoneShortName: "ZA",
        coordinates: [4.749979, 47.412075],
      },
      {
        departmentCode: "25",
        departmentName: "Doubs",
        isoCode: "FR-25",
        schoolZoneShortName: "ZA",
        coordinates: [6.307457, 47.217272],
      },
      {
        departmentCode: "39",
        departmentName: "Jura",
        isoCode: "FR-39",
        schoolZoneShortName: "ZA",
        coordinates: [5.591728, 46.79907],
      },
      {
        departmentCode: "58",
        departmentName: "Nièvre",
        isoCode: "FR-58",
        schoolZoneShortName: "ZA",
        coordinates: [3.681821, 47.137335],
      },
      {
        departmentCode: "70",
        departmentName: "Haute-Saône",
        isoCode: "FR-70",
        schoolZoneShortName: "ZA",
        coordinates: [6.012871, 47.590818],
      },
      {
        departmentCode: "71",
        departmentName: "Saône-et-Loire",
        isoCode: "FR-71",
        schoolZoneShortName: "ZA",
        coordinates: [4.619501, 46.678941],
      },
      {
        departmentCode: "89",
        departmentName: "Yonne",
        isoCode: "FR-89",
        schoolZoneShortName: "ZA",
        coordinates: [3.626542, 47.810206],
      },
      {
        departmentCode: "90",
        departmentName: "Territoire de Belfort",
        isoCode: "FR-90",
        schoolZoneShortName: "ZA",
        coordinates: [6.947931, 47.606837],
      },
    ],
    coordinates: [4.830839, 47.316236],
  },
  {
    regionCode: "28",
    regionName: "Normandie",
    isoCode: "FR-NOR",
    schoolZoneShortName: "ZB",
    timeZone: "Europe/Paris",
    slug: "normandie",
    departments: [
      {
        departmentCode: "14",
        departmentName: "Calvados",
        schoolZoneShortName: "ZB",
        isoCode: "FR-14",
        coordinates: [-0.433769, 49.053979],
      },
      {
        departmentCode: "27",
        departmentName: "Eure",
        isoCode: "FR-27",
        schoolZoneShortName: "ZB",
        coordinates: [1.063561, 49.148454],
      },
      {
        departmentCode: "50",
        departmentName: "Manche",
        isoCode: "FR-50",
        schoolZoneShortName: "ZB",
        coordinates: [-1.414142, 49.116465],
      },
      {
        departmentCode: "61",
        departmentName: "Orne",
        isoCode: "FR-61",
        schoolZoneShortName: "ZB",
        coordinates: [0.034851, 48.583381],
      },
      {
        departmentCode: "76",
        departmentName: "Seine-Maritime",
        isoCode: "FR-76",
        schoolZoneShortName: "ZB",
        coordinates: [1.156989, 49.590326],
      },
    ],
    coordinates: [-0.245012, 49.09545],
  },
  {
    regionCode: "32",
    regionName: "Hauts-de-France",
    isoCode: "FR-HDF",
    schoolZoneShortName: "ZB",
    timeZone: "Europe/Paris",
    slug: "hauts-de-france",
    departments: [
      {
        departmentCode: "02",
        departmentName: "Aisne",
        isoCode: "FR-02",
        schoolZoneShortName: "ZB",
        coordinates: [3.45097, 49.479355],
      },
      {
        departmentCode: "59",
        departmentName: "Nord",
        isoCode: "FR-59",
        schoolZoneShortName: "ZB",
        coordinates: [3.20406, 50.434006],
      },
      {
        departmentCode: "60",
        departmentName: "Oise",
        isoCode: "FR-60",
        schoolZoneShortName: "ZB",
        coordinates: [2.50564, 49.399018],
      },
      {
        departmentCode: "62",
        departmentName: "Pas-de-Calais",
        isoCode: "FR-62",
        schoolZoneShortName: "ZB",
        coordinates: [2.497439, 50.381139],
      },
      {
        departmentCode: "80",
        departmentName: "Somme",
        isoCode: "FR-80",
        schoolZoneShortName: "ZB",
        coordinates: [2.389903, 49.96157],
      },
    ],
    coordinates: [2.816916, 49.868958],
  },
  {
    regionCode: "44",
    regionName: "Grand Est",
    isoCode: "FR-GES",
    schoolZoneShortName: "ZB",
    slug: "grand-est",
    timeZone: "Europe/Paris",
    departments: [
      {
        departmentCode: "08",
        departmentName: "Ardennes",
        isoCode: "FR-08",
        schoolZoneShortName: "ZB",
        coordinates: [4.709835, 49.634965],
      },
      {
        departmentCode: "10",
        departmentName: "Aube",
        isoCode: "FR-10",
        schoolZoneShortName: "ZB",
        coordinates: [4.089277, 48.317772],
      },
      {
        departmentCode: "51",
        departmentName: "Marne",
        isoCode: "FR-51",
        schoolZoneShortName: "ZB",
        coordinates: [4.248071, 48.904449],
      },
      {
        departmentCode: "52",
        departmentName: "Haute-Marne",
        isoCode: "FR-52",
        schoolZoneShortName: "ZB",
        coordinates: [5.212101, 48.112613],
      },
      {
        departmentCode: "54",
        departmentName: "Meurthe-et-Moselle",
        isoCode: "FR-54",
        schoolZoneShortName: "ZB",
        coordinates: [6.10537, 48.887503],
      },
      {
        departmentCode: "55",
        departmentName: "Meuse",
        isoCode: "FR-55",
        schoolZoneShortName: "ZB",
        coordinates: [5.396658, 49.059767],
      },
      {
        departmentCode: "57",
        departmentName: "Moselle",
        isoCode: "FR-57",
        subdivisionShortName: "MO",
        schoolZoneShortName: "ZB",
        coordinates: [6.660133, 49.044461],
      },
      {
        departmentCode: "67",
        departmentName: "Bas-Rhin",
        isoCode: "FR-67",
        subdivisionShortName: "HR",
        schoolZoneShortName: "ZB",
        coordinates: [7.415949, 48.764522],
      },
      {
        departmentCode: "68",
        departmentName: "Haut-Rhin",
        isoCode: "FR-68",
        subdivisionShortName: "BR",
        schoolZoneShortName: "ZB",
        coordinates: [7.201035, 47.817528],
      },
      {
        departmentCode: "88",
        departmentName: "Vosges",
        isoCode: "FR-88",
        schoolZoneShortName: "ZB",
        coordinates: [6.304189, 48.233694],
      },
    ],
    coordinates: [5.416189, 48.705959],
  },
  {
    regionCode: "52",
    regionName: "Pays de la Loire",
    isoCode: "FR-PDL",
    schoolZoneShortName: "ZB",
    slug: "pays-de-la-loire",
    timeZone: "Europe/Paris",
    departments: [
      {
        departmentCode: "44",
        departmentName: "Loire-Atlantique",
        isoCode: "FR-44",
        schoolZoneShortName: "ZB",
        coordinates: [-1.734926, 47.301465],
      },
      {
        departmentCode: "49",
        departmentName: "Maine-et-Loire",
        isoCode: "FR-49",
        schoolZoneShortName: "ZB",
        coordinates: [-0.678045, 47.384117],
      },
      {
        departmentCode: "53",
        departmentName: "Mayenne",
        isoCode: "FR-53",
        schoolZoneShortName: "ZB",
        coordinates: [-0.660454, 48.162685],
      },
      {
        departmentCode: "72",
        departmentName: "Sarthe",
        isoCode: "FR-72",
        schoolZoneShortName: "ZB",
        coordinates: [0.235599, 48.011005],
      },
      {
        departmentCode: "85",
        departmentName: "Vendée",
        isoCode: "FR-85",
        schoolZoneShortName: "ZB",
        coordinates: [-1.422402, 46.728358],
      },
    ],
    coordinates: [-0.974108, 47.425382],
  },
  {
    regionCode: "53",
    regionName: "Bretagne",
    isoCode: "FR-BRE",
    schoolZoneShortName: "ZB",
    slug: "bretagne",
    timeZone: "Europe/Paris",
    departments: [
      {
        departmentCode: "22",
        departmentName: "Côtes-d'armor",
        isoCode: "FR-22",
        schoolZoneShortName: "ZB",
        coordinates: [-2.943113, 48.596217],
      },
      {
        departmentCode: "29",
        departmentName: "Finistère",
        isoCode: "FR-29",
        schoolZoneShortName: "ZB",
        coordinates: [-4.30232, 48.244427],
      },
      {
        departmentCode: "35",
        departmentName: "Ille-et-Vilaine",
        isoCode: "FR-35",
        schoolZoneShortName: "ZB",
        coordinates: [-1.777276, 48.280444],
      },
      {
        departmentCode: "56",
        departmentName: "Morbihan",
        isoCode: "FR-56",
        schoolZoneShortName: "ZB",
        coordinates: [-2.984379, 47.627768],
      },
    ],
    coordinates: [-3.477866, 48.144871],
  },
  {
    regionCode: "75",
    regionName: "Nouvelle-Aquitaine",
    isoCode: "FR-NAQ",
    schoolZoneShortName: "ZA",
    slug: "nouvelle-aquitaine",
    timeZone: "Europe/Paris",
    departments: [
      {
        departmentCode: "16",
        departmentName: "Charente",
        isoCode: "FR-16",
        schoolZoneShortName: "ZA",
        coordinates: [0.262957, 45.741113],
      },
      {
        departmentCode: "17",
        departmentName: "Charente-Maritime",
        isoCode: "FR-17",
        schoolZoneShortName: "ZA",
        coordinates: [-0.793718, 45.832494],
      },
      {
        departmentCode: "19",
        departmentName: "Corrèze",
        isoCode: "FR-19",
        schoolZoneShortName: "ZA",
        coordinates: [1.901582, 45.377903],
      },
      {
        departmentCode: "23",
        departmentName: "Creuse",
        isoCode: "FR-23",
        schoolZoneShortName: "ZA",
        coordinates: [1.915202, 46.071873],
      },
      {
        departmentCode: "24",
        departmentName: "Dordogne",
        isoCode: "FR-24",
        schoolZoneShortName: "ZA",
        coordinates: [0.745748, 45.13781],
      },
      {
        departmentCode: "33",
        departmentName: "Gironde",
        isoCode: "FR-33",
        schoolZoneShortName: "ZA",
        coordinates: [-0.508861, 44.767449],
      },
      {
        departmentCode: "40",
        departmentName: "Landes",
        isoCode: "FR-40",
        schoolZoneShortName: "ZA",
        coordinates: [-0.585044, 43.812626],
      },
      {
        departmentCode: "47",
        departmentName: "Lot-et-Garonne",
        isoCode: "FR-47",
        schoolZoneShortName: "ZA",
        coordinates: [0.504368, 44.38994],
      },
      {
        departmentCode: "64",
        departmentName: "Pyrénées-Atlantiques",
        isoCode: "FR-64",
        schoolZoneShortName: "ZA",
        coordinates: [-0.777902, 43.293375],
      },
      {
        departmentCode: "79",
        departmentName: "Deux-Sèvres",
        isoCode: "FR-79",
        schoolZoneShortName: "ZA",
        coordinates: [-0.361194, 46.589563],
      },
      {
        departmentCode: "86",
        departmentName: "Vienne",
        isoCode: "FR-86",
        schoolZoneShortName: "ZA",
        coordinates: [0.428883, 46.532391],
      },
      {
        departmentCode: "87",
        departmentName: "Haute-Vienne",
        isoCode: "FR-87",
        schoolZoneShortName: "ZA",
        coordinates: [1.2687, 45.92186],
      },
    ],
    coordinates: [0.078322, 45.159216],
  },
  {
    regionCode: "76",
    regionName: "Occitanie",
    isoCode: "FR-OCC",
    schoolZoneShortName: "ZC",
    slug: "occitanie",
    timeZone: "Europe/Paris",
    departments: [
      {
        departmentCode: "09",
        departmentName: "Ariège",
        isoCode: "FR-09",
        schoolZoneShortName: "ZC",
        coordinates: [1.503476, 42.956535],
      },
      {
        departmentCode: "11",
        departmentName: "Aude",
        isoCode: "FR-11",
        schoolZoneShortName: "ZC",
        coordinates: [2.338232, 43.14276],
      },
      {
        departmentCode: "12",
        departmentName: "Aveyron",
        isoCode: "FR-12",
        schoolZoneShortName: "ZC",
        coordinates: [2.631496, 44.308805],
      },
      {
        departmentCode: "30",
        departmentName: "Gard",
        isoCode: "FR-30",
        schoolZoneShortName: "ZC",
        coordinates: [4.004137, 43.960422],
      },
      {
        departmentCode: "31",
        departmentName: "Haute-Garonne",
        isoCode: "FR-31",
        schoolZoneShortName: "ZC",
        coordinates: [1.182843, 43.34134],
      },
      {
        departmentCode: "32",
        departmentName: "Gers",
        isoCode: "FR-32",
        schoolZoneShortName: "ZC",
        coordinates: [0.447546, 43.720332],
      },
      {
        departmentCode: "34",
        departmentName: "Hérault",
        isoCode: "FR-34",
        schoolZoneShortName: "ZC",
        coordinates: [3.341569, 43.558195],
      },
      {
        departmentCode: "46",
        departmentName: "Lot",
        isoCode: "FR-46",
        schoolZoneShortName: "ZC",
        coordinates: [1.616189, 44.607526],
      },
      {
        departmentCode: "48",
        departmentName: "Lozère",
        isoCode: "FR-48",
        schoolZoneShortName: "ZC",
        coordinates: [3.547536, 44.53028],
      },
      {
        departmentCode: "65",
        departmentName: "Hautes-Pyrénées",
        isoCode: "FR-65",
        schoolZoneShortName: "ZC",
        coordinates: [0.14542, 43.156191],
      },
      {
        departmentCode: "66",
        departmentName: "Pyrénées-Orientales",
        isoCode: "FR-66",
        schoolZoneShortName: "ZC",
        coordinates: [2.59005, 42.542448],
      },
      {
        departmentCode: "81",
        departmentName: "Tarn",
        isoCode: "FR-81",
        schoolZoneShortName: "ZC",
        coordinates: [2.173337, 43.798605],
      },
      {
        departmentCode: "82",
        departmentName: "Tarn-et-Garonne",
        isoCode: "FR-82",
        schoolZoneShortName: "ZC",
        coordinates: [1.290744, 44.116487],
      },
    ],
    coordinates: [2.102571, 43.74493],
  },
  {
    regionCode: "84",
    regionName: "Auvergne-Rhône-Alpes",
    isoCode: "FR-ARA",
    schoolZoneShortName: "ZA",
    slug: "auvergne-rhone-alpes",
    timeZone: "Europe/Paris",
    departments: [
      {
        departmentCode: "01",
        departmentName: "Ain",
        isoCode: "FR-01",
        schoolZoneShortName: "ZA",
        coordinates: [5.468741, 46.173123],
      },
      {
        departmentCode: "03",
        departmentName: "Allier",
        isoCode: "FR-03",
        schoolZoneShortName: "ZA",
        coordinates: [3.111639, 46.360089],
      },
      {
        departmentCode: "07",
        departmentName: "Ardèche",
        isoCode: "FR-07",
        schoolZoneShortName: "ZA",
        coordinates: [4.314696, 44.775981],
      },
      {
        departmentCode: "15",
        departmentName: "Cantal",
        isoCode: "FR-15",
        schoolZoneShortName: "ZA",
        coordinates: [2.738229, 45.032211],
      },
      {
        departmentCode: "26",
        departmentName: "Drôme",
        isoCode: "FR-26",
        schoolZoneShortName: "ZA",
        coordinates: [5.253157, 44.623857],
      },
      {
        departmentCode: "38",
        departmentName: "Isère",
        isoCode: "FR-38",
        schoolZoneShortName: "ZA",
        coordinates: [5.599029, 45.261772],
      },
      {
        departmentCode: "42",
        departmentName: "Loire",
        isoCode: "FR-42",
        schoolZoneShortName: "ZA",
        coordinates: [4.197503, 45.703368],
      },
      {
        departmentCode: "43",
        departmentName: "Haute-Loire",
        isoCode: "FR-43",
        schoolZoneShortName: "ZA",
        coordinates: [3.758202, 45.158436],
      },
      {
        departmentCode: "63",
        departmentName: "Puy-de-Dôme",
        isoCode: "FR-63",
        schoolZoneShortName: "ZA",
        coordinates: [3.118858, 45.708741],
      },
      {
        departmentCode: "69",
        departmentName: "Rhône",
        isoCode: "FR-69",
        schoolZoneShortName: "ZA",
        coordinates: [4.623249, 45.889921],
      },
      {
        departmentCode: "73",
        departmentName: "Savoie",
        isoCode: "FR-73",
        schoolZoneShortName: "ZA",
        coordinates: [6.408613, 45.49486],
      },
      {
        departmentCode: "74",
        departmentName: "Haute-Savoie",
        isoCode: "FR-74",
        schoolZoneShortName: "ZA",
        coordinates: [6.447215, 46.023091],
      },
    ],
    coordinates: [4.4029, 45.482715],
  },
  {
    regionCode: "93",
    regionName: "Provence-Alpes-Côte d'Azur",
    isoCode: "FR-PAC",
    schoolZoneShortName: "ZB",
    slug: "paca",
    timeZone: "Europe/Paris",
    departments: [
      {
        departmentCode: "04",
        departmentName: "Alpes-de-Haute-Provence",
        isoCode: "FR-04",
        schoolZoneShortName: "ZB",
        coordinates: [6.346072, 44.152901],
      },
      {
        departmentCode: "05",
        departmentName: "Hautes-Alpes",
        isoCode: "FR-05",
        schoolZoneShortName: "ZB",
        coordinates: [6.22342, 44.657922],
      },
      {
        departmentCode: "06",
        departmentName: "Alpes-Maritimes",
        isoCode: "FR-06",
        schoolZoneShortName: "ZB",
        coordinates: [7.1138, 43.781238],
      },
      {
        departmentCode: "13",
        departmentName: "Bouches-du-Rhône",
        isoCode: "FR-13",
        schoolZoneShortName: "ZB",
        coordinates: [5.126066, 43.37314],
      },
      {
        departmentCode: "83",
        departmentName: "Var",
        isoCode: "FR-83",
        schoolZoneShortName: "ZB",
        coordinates: [6.356999, 43.223493],
      },
      {
        departmentCode: "84",
        departmentName: "Vaucluse",
        isoCode: "FR-84",
        schoolZoneShortName: "ZB",
        coordinates: [5.153495, 44.128911],
      },
    ],
    coordinates: [6.085947, 43.528682],
  },
  {
    regionCode: "94",
    isoCode: "FR-20R",
    subdivisionShortName: "CO",
    schoolZoneShortName: "CO",
    slug: "corse",
    regionName: "Corse",
    timeZone: "Europe/Paris",
    departments: [
      {
        departmentCode: "2A",
        departmentName: "Corse-du-Sud",
        isoCode: "FR-2A",
        schoolZoneShortName: "CO",
        coordinates: [8.925533, 41.813641],
      },
      {
        departmentCode: "2B",
        departmentName: "Haute-Corse",
        isoCode: "FR-2B",
        schoolZoneShortName: "CO",
        coordinates: [9.098208, 42.561055],
      },
    ],
    coordinates: [8.976631, 42.074408],
  },
  {
    regionCode: "NC",
    slug: "nouvelle-caledonie",
    regionName: "Nouvelle Calédonie",
    isoCode: "FR-NC",
    timeZone: "Pacific/Noumea",
    departments: [
      {
        departmentCode: "988",
        departmentName: "Nouvelle Calédonie",
        isoCode: "FR-NC",
        coordinates: [0.078322, 45.159216],
      },
    ],
    coordinates: [0.078322, 45.159216],
  },
  {
    regionCode: "PO",
    slug: "polynesie-française",
    regionName: "Polynésie Française",
    isoCode: "FR-PF",
    coordinates: [-149.3667436, -17.650195245],

    timeZone: "Pacific/Tahiti",
    departments: [
      {
        departmentCode: "987",
        departmentName: "Polynésie Française",
        isoCode: "FR-PF",
        coordinates: [-149.3667436, -17.650195245],
      },
    ],
  },
  {
    regionCode: "SB",
    slug: "saint-barthelemy",
    isoCode: "FR-BL",
    subdivisionShortName: "BL",
    schoolZoneShortName: "BL",
    timeZone: "America/Martinique",
    regionName: "Saint-Barthélemy",
    coordinates: [0.235599, 48.011005],
    departments: [
      {
        departmentCode: "977",
        departmentName: "Saint-Barthélemy",
        isoCode: "FR-BL",
        subdivisionShortName: "BL",
        schoolZoneShortName: "BL",
        coordinates: [0.235599, 48.011005],
      },
    ],
  },
  {
    regionCode: "SM",
    slug: "saint-martin",
    regionName: "Saint-Martin",
    isoCode: "FR-MF",
    subdivisionShortName: "MF",
    schoolZoneShortName: "MF",
    timeZone: "America/Martinique",
    departments: [
      {
        departmentCode: "978",
        departmentName: "Saint-Martin",
        isoCode: "FR-MF",
        subdivisionShortName: "MF",
        schoolZoneShortName: "MF",
        coordinates: [-60.94789, 14.602637],
      },
    ],
    coordinates: [-60.94789, 14.602637],
  },
  {
    regionCode: "SP",
    slug: "saint-pierre-et-miquelon",
    regionName: "Saint-Pierre-et-Miquelon",
    isoCode: "FR-PM",
    schoolZoneShortName: "SP",
    timeZone: "America/Miquelon",
    coordinates: [4.619501, 46.678941],
    departments: [
      {
        departmentCode: "975",
        departmentName: "Saint-Pierre-et-Miquelon",
        isoCode: "FR-PM",
        schoolZoneShortName: "SP",
        coordinates: [4.619501, 46.678941],
      },
    ],
  },
  {
    regionCode: "WF",
    slug: "wallis-et-futuna",
    regionName: "Wallis-et-Futuna",
    isoCode: "FR-WF",
    timeZone: "Pacific/Wallis",
    coordinates: [-178.1202846, -14.3230751],
    departments: [
      {
        departmentCode: "986",
        departmentName: "Wallis-et-Futuna",
        isoCode: "FR-WF",
        coordinates: [-178.1202846, -14.3230751],
      },
    ],
  },
  {
    regionCode: "TF",
    slug: "terres-australes-francaises",
    regionName: "Terres australes françaises",
    isoCode: "FR-TF",
    timeZone: "Indian/Maldives",
    coordinates: [69.15949177338582, -49.253692233007015],
    departments: [
      {
        departmentCode: "984",
        departmentName: "Terres australes françaises",
        isoCode: "FR-TF",
        coordinates: [69.15949177338582, -49.253692233007015],
      },
    ],
  },
];
