/*
 * Soliguide: Useful information for those who need it
 *
 * SPDX-FileCopyrightText: © 2024 Solinum
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
export type LegacySeoCategoryId =
  | "accompagnement-emploi"
  | "accompagnement-social"
  | "accueil-jour"
  | "accueil"
  | "activites-diverses"
  | "activites-sportives"
  | "activites"
  | "acupuncture"
  | "addiction"
  | "alimentation"
  | "allergologie"
  | "animaux"
  | "atelier-cuisine"
  | "colis-bebe"
  | "bagagerie"
  | "bibliotheque"
  | "bien-etre"
  | "bon-alimentaire"
  | "boutique-solidaire"
  | "cardiologie"
  | "chauffeur"
  | "conseil-administratif"
  | "conseil-handicap"
  | "conseil-budget"
  | "conseil-logement"
  | "conseil-parents"
  | "conseil"
  | "covoiturage"
  | "cuisine-partagee"
  | "dentaire"
  | "depistage"
  | "dermatologie"
  | "distribution-repas"
  | "domiciliation"
  | "douche"
  | "echographie"
  | "ecrivain-public"
  | "endocrinologie"
  | "epicerie-sociale-solidaire"
  | "espace-famille"
  | "espace-repos"
  | "fontaine"
  | "formation-emploi"
  | "formation-francais"
  | "formation-numerique"
  | "frigo-solidaire"
  | "garde-enfants"
  | "gastro-enterologie"
  | "generaliste"
  | "gynecologie"
  | "halte-nuit"
  | "hebergement-citoyen"
  | "hebergement-et-logement"
  | "hebergement-long-terme"
  | "hebergement-urgence"
  | "hygiene"
  | "infirmerie"
  | "insertion-activite-economique"
  | "jardin-solidaire"
  | "kinesitherapie"
  | "laverie"
  | "mammographie"
  | "masques"
  | "materiel"
  | "musee"
  | "numerisation"
  | "nutrition"
  | "ophtalmologie"
  | "ordinateur"
  | "orthophonie"
  | "osteo"
  | "oto-rhino-laryngologie"
  | "panier-alimentaire"
  | "pedicure"
  | "permanence-juridique"
  | "permis"
  | "phlebologie"
  | "planification"
  | "pneumologie"
  | "point-information"
  | "prise"
  | "produits-hygiene"
  | "psychologie"
  | "radiologie"
  | "restauration-assise"
  | "rhumatologie"
  | "sante"
  | "soins-enfants"
  | "soutien-scolaire"
  | "specialistes-medecine"
  | "stomatologie"
  | "technologie"
  | "telephone"
  | "toilettes"
  | "transport-mobilite"
  | "urologie"
  | "vaccination"
  | "vehicule"
  | "vetements"
  | "veterinaire"
  | "wifi";
