/*
 * Soliguide: Useful information for those who need it
 *
 * SPDX-FileCopyrightText: © 2024 Solinum
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

import { CountryCodes } from "../../enums";
import { SpanishLanguageCode } from "../../enums/ES/SpanishLanguageCode.enum";
import { RegionDef } from "../../interfaces";

export const ES_REGIONS_DEF: Array<RegionDef<CountryCodes.ES>> = [
  {
    regionName: "Andalucía",
    regionCode: "01",
    isoCode: "ES-AN",
    subdivisionShortName: "AN",
    slug: "andalucia",
    timeZone: "Europe/Madrid",
    coordinates: [-4.5811614, 37.3399964],
    departments: [
      {
        coordinates: [-2.4628135, 36.8414197],
        departmentName: "Almería",
        departmentCode: "04",
        isoCode: "ES-AL",
        subdivisionShortName: "AN-AL",
        slug: "almeria",
      },
      {
        coordinates: [-6.2928976, 36.5297438],
        departmentName: "Cádiz",
        departmentCode: "11",
        isoCode: "ES-CA",
        subdivisionShortName: "AN-CA",
        slug: "cadiz",
      },
      {
        coordinates: [-4.7760138, 37.8845813],
        departmentName: "Córdoba",
        departmentCode: "14",
        isoCode: "ES-CO",
        subdivisionShortName: "AN-CO",
        slug: "cordoba",
      },
      {
        coordinates: [-3.5995337, 37.1734995],
        departmentName: "Granada",
        departmentCode: "18",
        isoCode: "ES-GR",
        subdivisionShortName: "AN-GR",
        slug: "granada",
      },
      {
        coordinates: [-6.9484945, 37.2575874],
        departmentName: "Huelva",
        departmentCode: "21",
        isoCode: "ES-H",
        subdivisionShortName: "AN-HL",
        slug: "huelva",
      },
      {
        coordinates: [-3.492055612037218, 37.9557275],
        departmentName: "Jaén",
        departmentCode: "23",
        isoCode: "ES-J",
        subdivisionShortName: "AN-JA",
        slug: "jaen",
      },
      {
        coordinates: [-4.4216366, 36.7213028],
        departmentName: "Málaga",
        departmentCode: "29",
        isoCode: "ES-MA",
        subdivisionShortName: "AN-MA",
        slug: "malaga",
      },
      {
        coordinates: [-5.9953403, 37.3886303],
        departmentName: "Sevilla",
        departmentCode: "41",
        isoCode: "ES-SE",
        subdivisionShortName: "AN-SE",
        slug: "sevilla",
      },
    ],
  },
  {
    regionName: "Aragón",
    regionCode: "02",
    isoCode: "ES-AR",
    subdivisionShortName: "AR",
    slug: "aragon",
    timeZone: "Europe/Madrid",
    coordinates: [-0.7639373, 41.3787291],
    departments: [
      {
        coordinates: [-0.029802662719165485, 42.13606145],
        departmentName: "Huesca",
        departmentCode: "22",
        isoCode: "ES-HU",
        subdivisionShortName: "AR-HU",
        slug: "huesca",
      },
      {
        coordinates: [-0.9229281876827901, 40.6005259],
        departmentName: "Teruel",
        departmentCode: "44",
        isoCode: "ES-TE",
        subdivisionShortName: "AR-TE",
        slug: "teruel",
      },
      {
        coordinates: [-0.8809428, 41.6521342],
        departmentName: "Zaragoza",
        departmentCode: "50",
        isoCode: "ES-Z",
        subdivisionShortName: "AR-ZG",
        slug: "zaragoza",
      },
    ],
  },
  {
    regionName: "Principado de Asturias",
    regionCode: "03",
    isoCode: "ES-AS",
    subdivisionShortName: "AS",
    slug: "asturias",
    timeZone: "Europe/Madrid",
    coordinates: [-5.94192, 43.3133868],
    departments: [
      {
        coordinates: [-5.94192, 43.3133868],
        departmentName: "Asturias",
        departmentCode: "33",
        isoCode: "ES-O",
        subdivisionShortName: "AS-AS",
        slug: "asturias",
      },
    ],
  },
  {
    regionName: "Illes Balears",
    coordinates: [2.8829184529439633, 39.613432],
    otherNames: [{ name: "Islas Baleares", lang: SpanishLanguageCode.ES }],
    regionCode: "04",
    isoCode: "ES-IB",
    subdivisionShortName: "IB",
    slug: "illes-balears",
    timeZone: "Europe/Madrid",
    departments: [
      {
        departmentName: "Illes Balears",
        otherNames: [{ name: "Islas Baleares", lang: SpanishLanguageCode.ES }],
        departmentCode: "07",
        isoCode: "ES-PM",
        subdivisionShortName: "IB-PM",
        slug: "illes-balears",
        coordinates: [2.8829184529439633, 39.613432],
      },
    ],
  },
  {
    regionName: "Canarias",
    regionCode: "05",
    isoCode: "ES-CN",
    subdivisionShortName: "CN",
    slug: "canarias",
    timeZone: "Atlantic/Canary",
    coordinates: [-15.6062305376665, 27.9580004],
    departments: [
      {
        coordinates: [-15.6062305376665, 27.9580004],
        departmentName: "Las Palmas",
        departmentCode: "35",
        isoCode: "ES-GC",
        subdivisionShortName: "CN-LP",
        slug: "las-palmas",
      },
      {
        coordinates: [-16.2507843, 28.467178],
        departmentName: "Santa Cruz de Tenerife",
        departmentCode: "38",
        isoCode: "ES-TF",
        subdivisionShortName: "CN-SC",
        slug: "santa-cruz-de-tenerife",
      },
    ],
  },
  {
    regionName: "Cantabria",
    regionCode: "06",
    isoCode: "ES-CB",
    subdivisionShortName: "CB",
    slug: "cantabria",
    timeZone: "Europe/Madrid",
    coordinates: [-4.0878382, 43.1595664],
    departments: [
      {
        coordinates: [-4.0878382, 43.1595664],
        departmentName: "Cantabria",
        departmentCode: "39",
        isoCode: "ES-S",
        subdivisionShortName: "CB-CB",
        slug: "cantabria",
      },
    ],
  },
  {
    regionName: "Castilla y León",
    regionCode: "07",
    isoCode: "ES-CL",
    subdivisionShortName: "CL",
    slug: "castilla-y-leon",
    timeZone: "Europe/Madrid",
    coordinates: [-5.1387401, 41.55005],
    departments: [
      {
        coordinates: [-4.7002172, 40.656478],
        departmentName: "Ávila",
        departmentCode: "05",
        isoCode: "ES-AV",
        subdivisionShortName: "CL-AV",
        slug: "avila",
      },
      {
        coordinates: [-3.696977, 42.343926],
        departmentName: "Burgos",
        departmentCode: "09",
        isoCode: "ES-BU",
        subdivisionShortName: "CL-BU",
        slug: "burgos",
      },
      {
        coordinates: [-5.971415104539984, 42.63414505],
        departmentName: "León",
        departmentCode: "24",
        isoCode: "ES-LE",
        subdivisionShortName: "CL-LE",
        slug: "leon",
      },
      {
        coordinates: [-4.616100410293067, 42.409632200000004],
        departmentName: "Palencia",
        departmentCode: "34",
        isoCode: "ES-P",
        subdivisionShortName: "CL-PL",
        slug: "palencia",
      },
      {
        coordinates: [-5.6640182, 40.9651572],
        departmentName: "Salamanca",
        departmentCode: "37",
        isoCode: "ES-SA",
        subdivisionShortName: "CL-SA",
        slug: "salamanca",
      },
      {
        coordinates: [-4.1172101, 40.9481192],
        departmentName: "Segovia",
        departmentCode: "40",
        isoCode: "ES-SG",
        subdivisionShortName: "CL-SG",
        slug: "segovia",
      },
      {
        coordinates: [-2.721938035449954, 41.60125045],
        departmentName: "Soria",
        departmentCode: "42",
        isoCode: "ES-SO",
        subdivisionShortName: "CL-SO",
        slug: "soria",
      },
      {
        coordinates: [-4.728562, 41.6521328],
        departmentName: "Valladolid",
        departmentCode: "47",
        isoCode: "ES-VA",
        subdivisionShortName: "CL-VA",
        slug: "valladolid",
      },
      {
        coordinates: [-5.942315044623113, 41.6857693],
        departmentName: "Zamora",
        departmentCode: "49",
        isoCode: "ES-ZA",
        subdivisionShortName: "CL-ZA",
        slug: "zamora",
      },
    ],
  },
  {
    regionName: "Castilla-La Mancha",
    regionCode: "08",
    isoCode: "ES-CM",
    subdivisionShortName: "CM",
    slug: "castilla-la-mancha",
    coordinates: [-2.6232332, 39.4177902],
    timeZone: "Europe/Madrid",
    departments: [
      {
        coordinates: [-1.8559154, 38.9950921],
        departmentName: "Albacete",
        departmentCode: "02",
        isoCode: "ES-AB",
        subdivisionShortName: "CM-AB",
        slug: "albacete",
      },
      {
        coordinates: [-3.8828744402485436, 38.959734749999996],
        departmentName: "Ciudad Real",
        departmentCode: "13",
        isoCode: "ES-CR",
        subdivisionShortName: "CM-CR",
        slug: "ciudad-real",
      },
      {
        coordinates: [-2.1313528, 40.0661031],
        departmentName: "Cuenca",
        departmentCode: "16",
        isoCode: "ES-CU",
        subdivisionShortName: "CM-CU",
        slug: "cuenca",
      },
      {
        coordinates: [-2.505930025884726, 40.7399963],
        departmentName: "Guadalajara",
        departmentCode: "19",
        isoCode: "ES-GU",
        subdivisionShortName: "CM-GU",
        slug: "guadalajara",
      },
      {
        coordinates: [-4.0239568, 39.8560679],
        departmentName: "Toledo",
        departmentCode: "45",
        isoCode: "ES-TO",
        subdivisionShortName: "CM-TO",
        slug: "toledo",
      },
    ],
  },
  {
    regionName: "Catalunya",
    otherNames: [{ name: "Cataluña", lang: SpanishLanguageCode.ES }],
    regionCode: "09",
    isoCode: "ES-CT",
    subdivisionShortName: "CT",
    slug: "cataluna",
    timeZone: "Europe/Madrid",
    coordinates: [1.5745043, 41.8523094],
    departments: [
      {
        coordinates: [2.1774322, 41.3828939],
        departmentName: "Barcelona",
        otherNames: [{ name: "Barcelona", lang: SpanishLanguageCode.ES }],
        departmentCode: "08",
        isoCode: "ES-B",
        subdivisionShortName: "CT-BA",
        slug: "barcelona",
      },
      {
        coordinates: [2.8199439, 41.9793006],
        departmentName: "Girona",
        otherNames: [{ name: "Gerona", lang: SpanishLanguageCode.ES }],
        departmentCode: "17",
        isoCode: "ES-GI",
        subdivisionShortName: "CT-GI",
        slug: "girona",
      },
      {
        coordinates: [0.6267842, 41.6147605],
        departmentName: "Lleida",
        otherNames: [{ name: "Lérida", lang: SpanishLanguageCode.ES }],
        departmentCode: "25",
        isoCode: "ES-L",
        subdivisionShortName: "CT-LD",
        slug: "lleida",
      },
      {
        coordinates: [1.2546057, 41.1172364],
        departmentName: "Tarragona",
        otherNames: [{ name: "Tarragona", lang: SpanishLanguageCode.ES }],
        departmentCode: "43",
        isoCode: "ES-T",
        subdivisionShortName: "CT-TG",
        slug: "tarragona",
      },
    ],
  },
  {
    regionName: "Comunidad Valenciana",
    coordinates: [-0.7654406, 39.6819591],
    otherNames: [
      { name: "Comunitat Valenciana", lang: SpanishLanguageCode.CA },
    ],
    regionCode: "10",
    isoCode: "ES-VC",
    subdivisionShortName: "VC",
    slug: "valenciana",
    timeZone: "Europe/Madrid",
    departments: [
      {
        departmentName: "Alicante",
        otherNames: [{ name: "Alacant", lang: SpanishLanguageCode.CA }],
        departmentCode: "03",
        isoCode: "ES-A",
        subdivisionShortName: "VC-AN",
        coordinates: [-0.4881708, 38.3436365],
        slug: "alicante",
      },
      {
        departmentName: "Castellón",
        otherNames: [{ name: "Castelló", lang: SpanishLanguageCode.CA }],
        departmentCode: "12",
        isoCode: "ES-CS",
        subdivisionShortName: "VC-CS",
        coordinates: [-0.06150521083301791, 40.25185675],
        slug: "castellon",
      },
      {
        departmentName: "Valencia",
        otherNames: [{ name: "València", lang: SpanishLanguageCode.CA }],
        departmentCode: "46",
        isoCode: "ES-V",
        subdivisionShortName: "VC-VN",
        coordinates: [-0.3763353, 39.4697065],
        slug: "valencia",
      },
    ],
  },
  {
    regionName: "Extremadura",
    coordinates: [-6.1529891, 39.1748426],
    otherNames: [{ name: "Estremaura", lang: SpanishLanguageCode.EXT }],
    regionCode: "11",
    isoCode: "ES-EX",
    subdivisionShortName: "EX",
    slug: "extremadura",
    timeZone: "Europe/Madrid",
    departments: [
      {
        coordinates: [-6.9701115, 38.878187],
        departmentName: "Badajoz",
        departmentCode: "06",
        isoCode: "ES-BA",
        subdivisionShortName: "EX-BA",
        slug: "badajoz",
      },
      {
        coordinates: [-6.3716761, 39.4745175],
        departmentName: "Cáceres",
        departmentCode: "10",
        isoCode: "ES-CC",
        subdivisionShortName: "EX-CC",
        slug: "caceres",
      },
    ],
  },
  {
    regionName: "Galicia",
    coordinates: [-7.863112, 42.61946],
    otherNames: [{ name: "Galicia", lang: SpanishLanguageCode.ES }],
    regionCode: "12",
    isoCode: "ES-GA",
    subdivisionShortName: "GA",
    slug: "galicia",
    timeZone: "Europe/Madrid",
    departments: [
      {
        coordinates: [-8.3959425, 43.3709703],
        departmentName: "A Coruña",
        otherNames: [{ name: "La Coruña", lang: SpanishLanguageCode.ES }],
        departmentCode: "15",
        isoCode: "ES-C",
        subdivisionShortName: "GA-AC",
        slug: "a-coruna",
      },
      {
        coordinates: [-7.456607166509571, 43.0396042],
        departmentName: "Lugo",
        otherNames: [{ name: "Lugo", lang: SpanishLanguageCode.ES }],
        departmentCode: "27",
        isoCode: "ES-LU",
        subdivisionShortName: "GA-LG",
        slug: "lugo",
      },
      {
        coordinates: [-7.53712401397051, 42.1939629],
        departmentName: "Ourense",
        otherNames: [{ name: "Orense", lang: SpanishLanguageCode.ES }],
        departmentCode: "32",
        isoCode: "ES-OR",
        subdivisionShortName: "GA-OR",
        slug: "ourense",
      },
      {
        coordinates: [-8.533254450398054, 42.3620772],
        departmentName: "Pontevedra",
        otherNames: [{ name: "Pontevedra", lang: SpanishLanguageCode.ES }],
        departmentCode: "36",
        isoCode: "ES-PO",
        subdivisionShortName: "GA-PV",
        slug: "pontevedra",
      },
    ],
  },
  {
    regionName: "Comunidad de Madrid",
    coordinates: [-3.7035825, 40.4167047],
    regionCode: "13",
    isoCode: "ES-MD",
    subdivisionShortName: "MD",
    slug: "madrid",
    timeZone: "Europe/Madrid",
    departments: [
      {
        coordinates: [-3.7035825, 40.4167047],
        departmentName: "Madrid",
        departmentCode: "28",
        isoCode: "ES-M",
        subdivisionShortName: "MD-MD",
        slug: "madrid",
      },
    ],
  },
  {
    regionName: "Región de Murcia",
    coordinates: [-1.1305431, 37.9923795],
    regionCode: "14",
    isoCode: "ES-MC",
    subdivisionShortName: "MC",
    slug: "murcia",
    timeZone: "Europe/Madrid",
    departments: [
      {
        coordinates: [-1.1305431, 37.9923795],
        departmentName: "Murcia",
        departmentCode: "30",
        isoCode: "ES-MU",
        subdivisionShortName: "MC-MU",
        slug: "murcia",
      },
    ],
  },
  {
    regionName: "Comunidad Foral de Navarra",
    coordinates: [-1.830787673361753, 42.61254875],
    otherNames: [{ name: "Nafarroako Foru", lang: SpanishLanguageCode.EU }],
    regionCode: "15",
    isoCode: "ES-NC",
    subdivisionShortName: "NC",
    slug: "navarra",
    timeZone: "Europe/Madrid",
    departments: [
      {
        coordinates: [-1.830787673361753, 42.61254875],
        departmentName: "Navarra",
        otherNames: [{ name: "Nafarroa", lang: SpanishLanguageCode.EU }],
        departmentCode: "31",
        isoCode: "ES-NA",
        subdivisionShortName: "NC-NA",
        slug: "navarra",
      },
    ],
  },
  {
    regionName: "País Vasco",
    otherNames: [{ name: "Euskadi", lang: SpanishLanguageCode.EU }],
    regionCode: "16",
    isoCode: "ES-PV",
    subdivisionShortName: "PV",
    slug: "pais-vasco",
    timeZone: "Europe/Madrid",
    coordinates: [-2.932792084695369, 43.2623215971685],
    departments: [
      {
        coordinates: [-2.6820829322126283, 42.844072249999996],
        departmentName: "Álava",
        otherNames: [{ name: "Araba", lang: SpanishLanguageCode.EU }],
        departmentCode: "01",
        isoCode: "ES-VI",
        subdivisionShortName: "PV-AA",
        slug: "alava",
      },
      {
        coordinates: [-2.2037955488327494, 43.144527800000006],
        departmentName: "Guipúzcoa",
        otherNames: [{ name: "Gipuzkoa", lang: SpanishLanguageCode.EU }],
        departmentCode: "20",
        isoCode: "ES-SS",
        subdivisionShortName: "PV-GP",
        slug: "gipuzkoa",
      },
      {
        coordinates: [-2.85163163999482, 43.238482000000005],
        departmentName: "Vizcaya",
        otherNames: [{ name: "Bizkaia", lang: SpanishLanguageCode.EU }],
        departmentCode: "48",
        isoCode: "ES-BI",
        subdivisionShortName: "PV-VZ",
        slug: "bizkaia",
      },
    ],
  },
  {
    regionName: "La Rioja",
    regionCode: "17",
    isoCode: "ES-RI",
    subdivisionShortName: "RI",
    slug: "la-rioja",
    timeZone: "Europe/Madrid",
    coordinates: [-2.4674917, 42.3285528],
    departments: [
      {
        coordinates: [-2.4674917, 42.3285528],
        departmentName: "La Rioja",
        departmentCode: "26",
        isoCode: "ES-LO",
        subdivisionShortName: "RI-LR",
        slug: "la-rioja",
      },
    ],
  },
  {
    regionName: "Ciudad Autónoma de Ceuta",
    regionCode: "18",
    isoCode: "ES-CE",
    subdivisionShortName: "CE",
    slug: "ceuta",
    timeZone: "Africa/Ceuta",
    coordinates: [-5.304138, 35.888361],
    departments: [
      {
        coordinates: [-5.304138, 35.888361],
        departmentName: "Ceuta",
        departmentCode: "51",
        isoCode: "ES-CE",
        subdivisionShortName: "CE",
        slug: "ceuta",
      },
    ],
  },
  {
    regionName: "Ciudad Autónoma de Melilla",
    regionCode: "19",
    isoCode: "ES-ML",
    subdivisionShortName: "ML",
    slug: "melilla",
    timeZone: "Africa/Ceuta",
    coordinates: [-2.9384440747926486, 35.29219605218153],
    departments: [
      {
        coordinates: [-2.9384440747926486, 35.29219605218153],
        departmentName: "Melilla",
        isoCode: "ES-ML",
        subdivisionShortName: "ML",
        departmentCode: "52",
        slug: "melilla",
      },
    ],
  },
];
